export interface BlogPostData {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  author: string;
  image: string;
  // Hand-written posts here use a plain paragraph array; posts generated by
  // the Laravel backend's Gemini integration come back as a single HTML
  // string (it's prompted to produce real <h2>/<ul>/<table> structure, which
  // a flat paragraph array can't represent). BlogPost.tsx renders either.
  content: string[] | string;
}

export const blogs: BlogPostData[] = [
  {
    id: "2026-supply-chain",
    title: "Navigating the 2026 Global Supply Chain for Analytical Reagents",
    excerpt:
      "As raw material availability shifts globally, strategic procurement is more critical than ever. Learn how we are securing supply lines for essential testing laboratories.",
    category: "Market Trends",
    date: "Nov 05, 2025",
    author: "Rakesh Sharma",
    image: "/images/lab_analytical.jpeg",
    content: [
      "The chemical supply chain has seen unprecedented volatility over the past few years. For laboratories relying on high-purity analytical reagents (AR grade) for critical compliance testing, stockouts are not just an inconvenience — they are a hard stop on production and quality assurance.",
      "To mitigate these risks, we have finalised the acquisition of three new climate-controlled distribution centres. This expansion allows us to increase our buffer stock of high-demand solvents like acetonitrile and methanol (HPLC grade) by over 150%, effectively shielding our B2B partners from global shipping delays.",
      "Moving into 2026, we are also rolling out direct ERP integration for our enterprise clients. This means automated re-ordering when batch stocks run low, and direct access to Material Safety Data Sheets (MSDS) and Certificates of Analysis (CoA) directly from our upcoming client portal.",
    ],
  },
  {
    id: "iso-9001-logistics",
    title: "Understanding ISO 9001:2015 within Chemical Logistics",
    excerpt:
      "How strict adherence to quality management systems prevents contamination during the transport of sensitive laboratory reagents.",
    category: "Compliance",
    date: "Oct 12, 2025",
    author: "Quality Team",
    image: "/images/stock_borosil.jpeg",
    content: [
      "ISO 9001:2015 isn't just a certificate on the wall — it's the backbone of how we receive, store, and dispatch every batch that passes through our facility.",
      "Every incoming lot is checked against its Certificate of Analysis before it's released to shelf. Outgoing shipments are packed under documented procedures specific to the hazard class of the product, with full chain-of-custody records retained for audit.",
    ],
  },
  {
    id: "ar-vs-lr-grade",
    title: "The Importance of AR Grade vs LR Grade Chemicals",
    excerpt:
      "A technical breakdown of purity levels and when to utilise Analytical Reagent grade over standard Laboratory Reagent parameters in modern testing.",
    category: "Technical Guide",
    date: "Sep 28, 2025",
    author: "Dr. Anjali Desai",
    image: "/images/gallery_7.jpeg",
    content: [
      "AR (Analytical Reagent) grade is formulated for accuracy-critical analytical work. LR (Laboratory Reagent) grade is for general lab use where trace impurities won't affect the outcome.",
      "Using a higher grade than necessary isn't 'extra safe' — it's an unnecessary cost. Using a lower grade than necessary risks contaminating your results. Match the grade to what the protocol actually demands.",
    ],
  },
  {
    id: "cold-storage-expansion",
    title: "Gayatri Enterprises Expands Cold Storage Capacity",
    excerpt:
      "We're excited to announce a 40% increase in our climate-controlled warehousing to better serve the growing biotechnology sector in the region.",
    category: "Company News",
    date: "Sep 15, 2025",
    author: "Company News",
    image: "/images/industry_pharma.jpeg",
    content: [
      "Temperature-sensitive reagents start degrading the moment they leave controlled storage. Our newly expanded cold-chain facility extends validated-range storage capacity by 40%, directly supporting the growing biotech and pharma client base in our region.",
    ],
  },
  {
    id: "solvent-disposal",
    title: "Proper Disposal Protocols for Halogenated Solvents",
    excerpt:
      "Safety first. Following local regulations and standardised procedures to responsibly handle and exhaust hazardous laboratory by-products.",
    category: "Safety",
    date: "Aug 30, 2025",
    author: "Safety Board",
    image: "/images/lab_glassware_zoom.jpeg",
    content: [
      "Halogenated solvents require segregated waste streams — never combine them with general organic waste. Our technical team can advise registered clients on compliant disposal routes for spent reagents.",
    ],
  },
];
