<?php

namespace App\Filament\Resources;

use App\Filament\Resources\InvoiceResource\Pages;
use App\Models\Invoice;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Support\Facades\Storage;

class InvoiceResource extends Resource
{
    protected static ?string $model = Invoice::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static ?string $navigationGroup = 'Sales';

    // Invoices are only ever generated by InvoiceService as part of order
    // confirmation — never created or edited by hand here.
    public static function canCreate(): bool
    {
        return false;
    }

    public static function canEdit($record): bool
    {
        return false;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('invoice_no')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('order.client.company_name')->label('Client')->searchable(),
                Tables\Columns\TextColumn::make('order.total')->label('Total')->money('INR'),
                Tables\Columns\TextColumn::make('order.payment_status')
                    ->label('Payment')
                    ->badge()
                    ->color(fn (?string $state) => match ($state) {
                        'paid' => 'success',
                        'unpaid' => 'warning',
                        default => 'gray',
                    }),
                Tables\Columns\TextColumn::make('order.payment_mode')
                    ->label('Mode')
                    ->formatStateUsing(fn (?string $state) => match ($state) {
                        'cash' => 'Cash',
                        'cheque' => 'Cheque',
                        'neft' => 'NEFT / Bank Transfer',
                        default => '—',
                    }),
                Tables\Columns\TextColumn::make('created_at')->dateTime('d M Y')->sortable(),
            ])
            ->defaultSort('created_at', 'desc')
            ->actions([
                Tables\Actions\Action::make('download')
                    ->label('Download PDF')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->action(fn (Invoice $record) => Storage::disk('local')->download($record->pdf_path, str_replace('/', '-', $record->invoice_no) . '.pdf'))
                    ->visible(fn (Invoice $record) => $record->pdf_path && Storage::disk('local')->exists($record->pdf_path)),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListInvoices::route('/'),
        ];
    }
}
